### ISSUE TITLE
Cannot install Craft from project config with a 'default' calendar

### ISSUE THREAD

**Issue by wallacio** [solspace/craft3-calendar#51]
When deploying a site for the first time with `craft install` and using project config, an error is generated suggesting that the 'default' calendar already exists. I'm guessing that this calendar is created as part of the installation, then project-config comes along and tries to create it again.

A couple of experiments shows that a workaround presents other problems - I changed the 'default' handle in dev to something else, which allows the installation to complete with the pre-configured calendar from project config. However, the plugin still insists on creating a 'default' calendar during `craft install` in production (even though one no longer exists in dev) and therefore modifies project config on what is a production environment.

Here's a snippet from the logs:
```
> applying existing project config ... Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'default' for key 'handle'
The SQL being executed was: 
INSERT INTO `calendar_calendars` (`uid`, `name`, `handle`, `description`, `color`, `descriptionFieldHandle`, `locationFieldHandle`, `icsHash`, `icsTimezone`, `titleFormat`, `titleLabel`, `hasTitleField`, `allowRepeatingEvents`, `fieldLayoutId`, `dateCreated`, `dateUpdated`) 
VALUES ('019e3025-be7a-432c-9188-c465020d97eb', 'Default', 'default', 'The default calendar', '#023F58', '0', '0', NULL, 'floating', '', 'Title', 1, 1, 1, '2021-07-15 16:06:54', '2021-07-15 16:06:54') 
(/home/aadaorg/public_html/vendor/yiisoft/yii2/db/Schema.php:678)
```

**Steps to reproduce**

1. Deploy a git repository of a Craft site which contains a single, pre-configured Calendar with the handle 'default'
2. Run ./craft install

**Craft & Plugin Info**

- Craft Version: 3.7.0
- Calendar Version: 3.3.2
- Calendar Edition: Lite
- Fresh Install or Upgrade: Fresh install of Craft with PC.

YAML from project config:

```yaml
allowRepeatingEvents: true
color: '#023F58'
description: 'The default calendar'
descriptionFieldHandle: '0'
fieldLayout:
  tabs:
    -
      elements:
        -
          fieldUid: 3881eeff-1f46-4329-a193-0ccd0711348b # Featured image
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 50
        -
          fieldUid: 73958d86-d825-444f-8b4f-89de8224e76c # Summary image
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 50
        -
          fieldUid: f3662c0e-a479-4626-b5dc-dfeed990629e # Intro text
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 100
        -
          fieldUid: e0efe2d2-bc06-4c02-9778-3639b4b699c9 # Venue
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 50
        -
          fieldUid: 9e268147-2302-4125-af91-e69c300a0cb8 # Price
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 50
        -
          fieldUid: 4976fa92-3408-415e-84d0-deec9a3e2ec4 # Description
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 100
        -
          type: craft\fieldlayoutelements\HorizontalRule
        -
          fieldUid: 5aba0f41-8bbb-43bb-9205-55585b91ca29 # Website
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 50
        -
          fieldUid: a599f193-fe3b-49d1-8351-5ef871c97ab8 # Booking link
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 50
        -
          type: craft\fieldlayoutelements\HorizontalRule
        -
          fieldUid: b786d9d9-1009-4da9-9763-d0f83c1dfc3e # Contact email
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 50
        -
          fieldUid: 7c3a5c79-3985-4ee4-a035-8638f862c60d # Contact telephone
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 50
        -
          fieldUid: c0713327-146a-4571-b192-eb19bc5caa52 # Organiser
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 50
        -
          fieldUid: 1082e1c8-1c15-4f25-a683-e5fcc2120ffd # Organiser website
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 50
      name: Details
      sortOrder: 1
    -
      elements:
        -
          fieldUid: 7a2d636a-d371-41fd-9a55-ecbe51ad518c # SEO
          instructions: null
          label: null
          required: false
          tip: null
          type: craft\fieldlayoutelements\CustomField
          warning: null
          width: 100
      name: Meta
      sortOrder: 2
  uid: 33eaad16-a22b-48f2-8ff0-bd099eef7f92
handle: default
hasTitleField: true
icsHash: null
icsTimezone: floating
locationFieldHandle: '0'
name: Default
siteSettings:
  d32dfeff-4b5a-4f75-839c-62d31058793b:
    enabledByDefault: true
    hasUrls: true
    siteId: 5ce0eb20-760e-42c2-8576-640f55aee930 # AADA
    template: events/_entry
    uriFormat: 'event/{slug}'
titleFormat: ''
titleLabel: Title
```
